<div autocomplete="<?= "bday" ?>"></div>
<input autocomplete="<?= "bday" ?>"/>
<div autocomplete="<?php echo "bday" ?>"></div>
<input autocomplete="<?php echo "bday" ?>"/>

<input type="url" autocomplete="<?= "bday" ?>"/>
<input type="date" autocomplete="<?= "bday" ?>"/>
<input type="text" autocomplete="<?= "bday" ?>"/>
<select autocomplete="<?= "bday" ?>"></select>
<textarea autocomplete="<?= "bday" ?>"></textarea>
<input type="hidden" autocomplete="<?= "bday" ?>"/>

<input type="url" autocomplete="<?php echo "bday" ?>"/>
<input type="date" autocomplete="<?php echo "bday" ?>"/>
<input type="text" autocomplete="<?php echo "bday" ?>"/>
<select autocomplete="<?php echo "bday" ?>"></select>
<textarea autocomplete="<?php echo "bday" ?>"></textarea>
<input type="hidden" autocomplete="<?php echo "bday" ?>"/>
