name: QA
on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches:
      - master
      - branch-*
      - dogfood-*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  plugin_qa:
    name: Plugin QA
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event.workflow_run.conclusion == 'success' &&
       github.actor != 'dependabot[bot]' &&
       github.event.workflow_run.event != 'merge_group' &&
       (github.event.workflow_run.head_branch == 'master' ||
        startsWith(github.event.workflow_run.head_branch, 'branch-') ||
        startsWith(github.event.workflow_run.head_branch, 'dogfood-') ||
        github.event.workflow_run.event == 'pull_request'))
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        sq_version:
          - LATEST_RELEASE
          - DEV
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@f8dfbcc150159126838e44b882bf34bd98fd90f3 # v2025.1.3
        with:
          version: 2025.1.3
      - uses: SonarSource/ci-github-actions/setup-orchestrator-maven-deps@v1
      - name: Run Plugin QA
        env:
          SQ_VERSION: ${{ matrix.sq_version }}
        run: |
          cd its/plugin
          mvn verify \
            -Dsonar.runtimeVersion=${SQ_VERSION} \
            -Dmaven.test.redirectTestOutputToFile=false \
            -B -e -V

  ruling:
    name: Ruling
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event.workflow_run.conclusion == 'success' &&
       github.actor != 'dependabot[bot]' &&
       github.event.workflow_run.event != 'merge_group' &&
       (github.event.workflow_run.head_branch == 'master' ||
        startsWith(github.event.workflow_run.head_branch, 'branch-') ||
        startsWith(github.event.workflow_run.head_branch, 'dogfood-') ||
        github.event.workflow_run.event == 'pull_request'))
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          submodules: true
      - uses: jdx/mise-action@f8dfbcc150159126838e44b882bf34bd98fd90f3 # v2025.1.3
        with:
          version: 2025.1.3
      - uses: SonarSource/ci-github-actions/setup-orchestrator-maven-deps@v1
      - name: Run Ruling Tests
        run: |
          cd its/ruling
          mvn verify \
            -Dsonar.runtimeVersion=LATEST_RELEASE \
            -Dmaven.test.redirectTestOutputToFile=false \
            -B -e -V
